name: Build React App

on:
  push:
    branches:
      - main  # Or your specific branch for production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.0'  # Your Node.js version

      - name: Install dependencies
        working-directory: frontend  # Specify the frontend directory
        run: npm install

      - name: Build the React app
        working-directory: frontend  # Specify the frontend directory
        run: npm run build

      - name: Upload build folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: react-build
          path: frontend/build  # Adjust to the path where React outputs the built bundle
