name: Build and Release React App

on:
  workflow_dispatch:  # manual-only

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.0'

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build the React app
        working-directory: frontend
        run: CI=false npm run build

      - name: Create temporary directory for zipping
        run: mkdir package

      - name: Copy build and backend to temporary directory
        run: |
          cp -r frontend/build package/
          cp -r backend package/

      - name: Zip the contents of the temporary directory
        run: tar -zcvf build.tar.gz package

      - name: Create or Update Release
        id: create_or_update_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: build.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}