name: Build and Release React App

on:
  workflow_dispatch:  # manual-only

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.0'

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build the React app
        working-directory: frontend
        run: CI=false npm run build

      - name: Zip the React build
        working-directory: frontend
        run: zip -r build.zip build

      - name: Create or Update Release
        id: create_or_update_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: frontend/build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}